
version: "3"
services:
    mariadb:
        image: mariadb
        container_name: mariadb
        ports:
            - 3306:3306
        volumes:
            - ./db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        restart: unless-stopped

networks:
    default:
        external:
            name: nginx-proxy